[FEAT] 히스토리 마크업
team-vera6/career-client pull request #45
Opened 2024-07-30 09:04 UTC by MeaninGood

### 작업내용
- 히스토리 구조 마크업
- 히스토리 -> 회고 및 회고 시트 마크업 (수정, 삭제 로직은 반영x)

### 기타 수정사항
- lnb
  - 리포트 -> 히스토리로 네이밍 변경됨에 따라 path 변경하였습니다.
  - history 페이지가 history/review, history/memo로 개발되면서 menu.path와 currentPathname 비교하는 로직 변경되었습니다.
- 회고 페이지에서 만든 컴포넌트를 끌어 쓰면서 하이라이트/로우라이트 관련 css 수정되었습니다.

### 참고사항
- 메모 페이지는 브랜치 새로 파서 작업하겠습니다~

2024-07-31 04:21 UTC, msdio reviewed
저는 로직이나 jsx에 적절한 개행이 가독성에 큰 영향을 준다고 생각하는데... 개행을 적절하게 넣어주시면 더 읽기 수월해질 것 같아요

2024-07-31 04:21 UTC, msdio commented on src/app/review/_components/last-review/LastReviewItem.tsx
> +          <p className="truncate font-body-14 text-text-strong">{project}</p>
`truncate`라는게 있었군요..? 매번 3개 다 일일이 선언했었는데... 하나 배워갑니다

2024-07-31 04:21 UTC, msdio commented on src/app/(with-navigation)/history/review/_components/ReviewDetailSheet/ReviewDetailSheet.tsx
> +          <h1 className="font-head-28 text-text-strong">6월 4주차</h1>
h1 태그가 여기 있는게 어색한 것 같아요. 차라리 페이지의 `히스토리`나 `회고` 가 h1으로 더 적절할 것 같아요.

2024-07-31 04:21 UTC, msdio commented on src/app/(with-navigation)/history/review/_components/ReviewDetailSheet/ReviewDetailSheet.tsx
> +  setShowDetail: Dispatch<SetStateAction<boolean>>;
저는 이런 setter 함수를 아래처럼 타이핑 하곤 하는데요.
```typescript
setShowDetail: (show: boolean) => void;
```

하나로 통일되면 좋지 않을까 싶습니다!

2024-07-31 04:21 UTC, msdio commented on src/app/(with-navigation)/history/review/_components/ReviewDetailSheet/ReviewDetail.tsx
> +        </p>
전체를 div로 감싸고 `하이라이트` 텍스트를 p 태그로 감싸는게 더 적절하지 않을까요?

2024-07-31 04:21 UTC, msdio commented on src/app/(with-navigation)/history/review/_components/HistoryReview/HistoryReview.tsx
> +      {showDetail && (
이런데에는 개행이 추가되어도 좋지 않을까요

2024-07-31 04:21 UTC, msdio commented on src/app/(with-navigation)/history/_components/review/Score.tsx
> +  className?: HTMLAttributes<HTMLDivElement>['className'];
갑자기 든 생각인데 `HTMLAttributes<HTMLDivElement>['className']` 이 타입 제네릭 써서 따로 빼는건 어떨까요 `ClassName<T>` 이런식으로

2024-07-31 04:26 UTC, msdio commented on src/app/(with-navigation)/history/review/_components/ReviewDetailSheet/ReviewDetailSheet.tsx
> +  setShowDetail: Dispatch<SetStateAction<boolean>>;
제 방식으로 통일하자는게 아니니 의견 남겨주세요!

2024-08-01 07:28 UTC, MeaninGood commented on src/app/(with-navigation)/history/review/_components/ReviewDetailSheet/ReviewDetailSheet.tsx
> +  setShowDetail: Dispatch<SetStateAction<boolean>>;
음 저는 개인적으로 setter라는 걸 명시하고,
특정 동작 수행 시 어떤 값의 상태가 변화한다는 걸 알 수 있도록 SetStateAction 타입 선언을 선호하긴 하는데..! 
말씀주신 대로 하나로 통일하면 좋을 것 같아용~~!!!

2024-08-01 07:36 UTC, MeaninGood commented on src/app/(with-navigation)/history/_components/review/Score.tsx
> +  className?: HTMLAttributes<HTMLDivElement>['className'];
완전 동의합니다 냅다 만들어~~!

2024-08-01 07:40 UTC, MeaninGood commented on src/app/(with-navigation)/history/_components/review/Score.tsx
> +  className?: HTMLAttributes<HTMLDivElement>['className'];
만들어서 반영해뒀습니다~! 🙂

2024-08-01 08:24 UTC, MeaninGood commented on src/app/(with-navigation)/history/review/_components/ReviewDetailSheet/ReviewDetail.tsx
> +          <CheckboxInput value="ㅇㅇㅇ" checked />
반영 완료오~했습니당!!

2024-08-01 08:39 UTC, MeaninGood commented
@msdio 반영 완료했습니다~~!
확인 한번 부탁드려요 !!

2024-08-01 08:54 UTC, msdio reviewed
review > components에 LastReview 라는 컴포넌트가 남아잇긴 한데.. 다음 작업하면서 같이 바꿔주세요!

2024-08-01 08:57 UTC, msdio requested changes

2024-08-01 08:57 UTC, msdio commented on src/app/(with-navigation)/history/review/_components/HistoryReview/HistoryReview.tsx
엥 여기가 구조가 좀 이상한데... 

dummy map돌리는거랑 EmptyHistoryReview가 조건부 렌더링이 되고 
ReviewDetailSheet가 따로 빠지는게 맞지 않을까요?

2024-08-01 08:58 UTC, msdio commented on src/components/inputs/deletable-input/DeletableInput.tsx
시간되면 스토리북도 같이 작성해주세요 ~

2024-08-01 09:03 UTC, MeaninGood commented on src/components/inputs/deletable-input/DeletableInput.tsx
[94ee152](https://github.com/team-vera6/career-client/pull/45/commits/94ee15297ceb2b9a50c6d8e918911326dcf6e098)

스토리북 같이 추가해 뒀습니당 !

2024-08-01 09:03 UTC, MeaninGood commented on src/app/(with-navigation)/history/review/_components/HistoryReview/HistoryReview.tsx
으아아 급하게 하느라.. 감삽니당 ㅋㅋㅋㅋ

2024-08-01 09:05 UTC, msdio commented on src/app/(with-navigation)/history/review/_components/HistoryReview/HistoryReview.tsx
>          </>
이 태그는 지워도 될것같아요 의미없이 한번 더 감싸져있네요

2024-08-01 09:06 UTC, msdio approved these changes
코멘트 확인하시고 머지해도 좋을것같습니다~ 고생하셨어요

2024-08-01 09:55 UTC, merged