[FEAT] 회원가입 api 연
team-vera6/career-client pull request #53
Opened 2024-08-18 14:59 UTC by MeaninGood

# 작업 내용

### 주요 내용
- 로그인 / 회원가입 관련 atom, api, hook 개발했습니다.
- 화면 처리 관련 로직 개발했습니다.

### router path 변경
- api 연동 이슈로 router path 변경했습니다. (sign-up -> enter-email, email -> email-verification)

### Number Input
- 인증번호 입력 시 Number Input에 자동 focus 이벤트가 필요해서, ref props를 넘겨주기 위해 forwardRef 추가했습니다.

### 유효성 검사
- 인증코드 작성 페이지 (auth/email-verification)
  - 숫자만 입력 가능하도록 개발
  - 모든 코드 입력 시 확인 버튼 클릭되도록 개발
- 비밀번호 입력 페이지 (auth/password) 
  - 비밀번호 대/소문자, 숫자 + 8자리
  - 비밀번호 일치 여부

2024-08-18 15:00 UTC, MeaninGood commented
이메일 유효성 검사 로직 추가 필요

2024-08-19 14:23 UTC, msdio commented
`회원가입 api 연` 은 뭔가요

2024-08-19 15:33 UTC, msdio requested changes
#### 눈에 보이는 이슈가 꽤 있어서... 고생하셨는데 괜히 트집 왕창 잡는 것 같아 죄송합니다 😢

1. 아직도 린트가 안먹어요.... 왜죠
![image](https://github.com/user-attachments/assets/b9249f7d-d286-4567-9d32-996c828a76f3)

2. 혹시 이메일 전송 잘 되나요? 저는 안오네요.. 이거 때문에 비밀번호  (추가 : 오긴 하는데 굉장히 오래 걸립니다... 한 10분 걸리는 것 같아요)

3. 가입한 이메일을 입력해도 이메일이 전송됩니다 ㅜ 
4. 인증번호 입력 화면에서 백스페이스를 누르면 이전 input으로 돌아가야 할 것 같아요!
![image](https://github.com/user-attachments/assets/594903ae-8bcc-4b31-904d-10bf66108072)
5. 시간이 만료된 후 재전송 되면 타이머가 재시작 해야 할 것 같아요! (시간이 만료되지 않았을 때 재전송을 하면 타이머가 초기화 되네요)
![image](https://github.com/user-attachments/assets/caa0696b-0593-4ba2-b4f7-daa41fe13653)
6. 이메일 입력 페이지에서 이메일 형식이 유효하지 않으면 아예 api 요청을 보내지 않는게 낫지 않을까요? 백엔드에서 검증을 한다고 해도 프론트에서 검증을 해서 의미없는 api 요청을 줄이는 것도 좋을 것 같아요
7. 비밀번호 유효성 검증 에러 문구가 사라지지 않네요 ㅠ
![image](https://github.com/user-attachments/assets/3b70c2d3-a61f-486b-b535-3b3402905f92)
8. 위의 7번 이슈 때문에 완료 버튼도 활성화가 안돼요
![image](https://github.com/user-attachments/assets/428dfb5e-3ec6-44ad-b7c8-ed8fe0376d2f)
9. 회원가입 완료 후 보여지는 모달은 아직 작업이 안된게 맞겠죠? setIsSignUp이라는 함수는 사용하고 있는데 모달은 안뜨길래...

2024-08-19 15:33 UTC, msdio commented on src/apis/auth/post.ts
> +  return { errorMessage: 'Unknown error' };
갑자기 든 의문인데, 서버에서 오는 에러는 `ErrorResponseType` 형태로 리턴하는데 이걸 굳이 errorMessage만 존재하는 형태로 바꿔서 리턴하시는 이유가 있을까요?

2024-08-19 15:33 UTC, msdio commented on src/apis/auth/post.ts
> +    return { errorMessage: 'Unknown error' };
여기는 위에서 만드신 `returnError` 함수를 사용하지 않으신 것 같아요!

2024-08-19 15:33 UTC, msdio commented on src/apis/auth/post.ts
> +      'auth/email/verification',
url에 위에 두 개 함수는 `/` 로 시작하는데, 여기는 `/` 없이 auth로 시작하네요.. `/` 붙은걸로 통일해주시면 좋을 것 같아요

2024-08-19 15:33 UTC, msdio commented on src/apis/auth/post.ts
> +
여기 로직은 useUser 훅에 있는 함수(`userLogin`)로 위임하는게 좋을 것 같아요. api 통신이 이루어지는 코드들만 위치해있는게 문맥상으로 더 통일성이 있을 것 같은데 어떻게 생각하시나요?

2024-08-19 15:33 UTC, msdio commented on src/apis/auth/post.ts
> +    return res;
여기 사이 개행이 있는 곳도 있고 없는 곳도 있어서... 사소한 디테일이지만 통일해주시면 좋을 것 같아요

2024-08-19 15:33 UTC, msdio commented on src/apis/index.ts
> +  // baseURL: 'https://api-pitstop.site/',
모든 api url이 `/` 로 시작하기 때문에, baseURL의 맨 마지막에 있는 `/`는 없애주는게 더 자연스러울 것 같아요

2024-08-19 15:33 UTC, msdio commented on src/app/auth/email-verification/components.tsx
> +  const INTERVAL = 1000;
상수 값들은 함수 밖으로 빼주세요!

2024-08-19 15:33 UTC, msdio commented on src/app/auth/email-verification/components.tsx
> +  const [codeArray, setCodeArray] = useState(new Array(6).fill(''));
숫자들인데 string으로 변환해서 사용하시는 이유가 있나요?

2024-08-19 15:33 UTC, msdio commented on src/app/auth/email-verification/components.tsx
> +    if (val !== '' && !/^[0-9]$/.test(val)) return;
위에 time_limit과 interval 값들을 상수화 한 것 처럼 정규식도 상수로 관리하면 더 보기 편할 것 같아요

2024-08-19 15:33 UTC, msdio commented on src/hooks/useUser.tsx
> +  const userEmailVerification = async (emailid: string, code: string) => {
`emailid` 가 카멜케이스인 `emailId` 가 되어야 할 것 같아요

2024-08-19 15:33 UTC, msdio commented on src/app/auth/email-verification/components.tsx
> +  };
`userEmailCheck` 함수가 Promise를 리턴하는 함수라서, reset 함수도 async를 명시해주는게 좋을 것 같아요.

2024-08-19 15:33 UTC, msdio commented on src/app/auth/email-verification/components.tsx
> +  }, [currentTime]);
timer 관련된 로직도 `useTimer` 라는 훅을 통해서 관리하면, 로직의 분리도 그렇고 나중에 다른 인증(예: 핸드폰 인증)이 추가될 경우에 재사용도 용이할 것 같아요

2024-08-19 15:33 UTC, msdio commented on src/app/auth/email-verification/components.tsx
> +  }, [codeArray, isTimeExpired]);
로직이 한눈에 들어오지 않고, 나중에 다른 조건이 추가되는 경우 확장이 거의 불가능할 것 같아요.

차라리 
- isTimeExpired인 경우 return false, 
- isAllValues가 false인 경우 return false
- 마지막에 return true

이렇게 early return 으로 하면 좀 더 코드가 명확해지지 않을까요? 제 생각에는 과도한 숏코딩이라는 생각이 들어서...

2024-08-19 15:33 UTC, msdio commented on src/app/auth/email-verification/components.tsx
> +      <form
개행이 들어가면 좋을 것 같아요

2024-08-19 15:33 UTC, msdio commented on src/app/auth/email-verification/components.tsx
> +              ref={(el: HTMLInputElement | null) =>
여기는 `HTMLInputElement | null`로 ts가 추론이 가능해서 명시하지 않아도 괜찮을 것 같아요

2024-08-19 15:33 UTC, msdio commented on src/app/auth/email-verification/components.tsx
> +        <p
개행이 들어가면 좋을 것 같아요

2024-08-19 15:33 UTC, msdio commented on src/app/auth/email-verification/components.tsx
> +        <button
개행이 들어가면 좋을 것 같아요

2024-08-19 15:33 UTC, msdio commented on src/app/auth/email-verification/components.tsx
> +            : `${minutes}:${seconds}`}
className도, 내부 텍스트도 달라진다면 아예 다른 dom으로 다뤄도 충분할 것 같은데.. isTimeExpired 여부에 따라 아예 별도의 p 태그를 만드는 건 어떤가요? 아래처럼요

```tsx
{isTimeExpired ? <p>...</p> : <p>...</p>}
```

2024-08-19 15:33 UTC, msdio commented on src/app/auth/email-verification/components.tsx
> +          메일이 오지 않으셨나요?{'\n'}스팸함을 확인하거나 인증 메일을{' '}
개행만 리터럴로 처리하기보다는 차라리 전체를 리터럴로 만드는게 더 나을 것 같기도 해요! 의견 남겨주세요

```
{'메일이 오지 않으셨나요?\n스팸함을 확인하거나 인증 메일을'}
```

2024-08-19 15:33 UTC, msdio commented on src/app/auth/email-verification/components.tsx
> +          <span
여기는 시멘틱 태그의 목적에 맞게 `strong` 태그를 사용하면 더 좋을 것 같아요!

2024-08-19 16:10 UTC, msdio commented on src/hooks/useUser.tsx
>    // login
메서드마다 달아놓은 주석들이 큰 의미는 없어보이는데, 지우는게 어떨까요?

2024-08-19 16:10 UTC, msdio commented on src/hooks/useUser.tsx
> +    if ('isVerified' in res && res.isVerified) {
음... 뭔가 조건을 다르게 바꿀 방법이 없을까요 뭔가뭔가 어색한데

2024-08-19 16:10 UTC, msdio commented on src/apis/auth/post.ts
> +}: SignUpResponse) => {
못찾을뻔했네... 타입 명이 `SignUpRequest`가 되는게 맞을 것 같아요

2024-08-19 16:10 UTC, msdio commented on src/hooks/useUser.tsx
> +      setUserToken((prev) => ({ ...prev, accessToken: res.token as string }));
여기 제가 이해가 안돼요.. signUp 함수의 response에 token이라는 프로퍼티가 없는데...?

2024-08-19 16:10 UTC, msdio commented on src/utils/parse.ts
> +  if (!emailPattern) return '';
emailPattern이 아니라 email 이 없는 경우에 return이 되는게 맞겠죠?

2024-08-19 16:10 UTC, msdio commented on src/stores/user/signUpAtom.ts
1. 이 값을 전역상태로 관리하시는 이유가 뭔가요?
2. 이 값이 회원가입 완료 후 true로 변경하는 것은 확인됐는데, 언제 false로 돌아오나요?

2024-08-22 14:40 UTC, MeaninGood commented on src/apis/auth/post.ts
> +  return { errorMessage: 'Unknown error' };
> 갑자기 든 의문인데, 서버에서 오는 에러는 `ErrorResponseType` 형태로 리턴하는데 이걸 굳이 errorMessage만 존재하는 형태로 바꿔서 리턴하시는 이유가 있을까요?

error response에서 정해진 응답값 (response)가 있는 경우만 ErrorResponseType으로 옵니다! 이외에 정해지지 않은 에러는 그대로 reject되어 전달되기 때문에 별도의 errorMessage를 리턴해주는 것입니다.

errorMessage로 리턴하는 이유는, toast 메세지를 띄우기 위해서인데요.
에러 코드가 정해진 경우에는 LOGIN_ERROR_MESSAGE의 텍스트를 전달합니다.
지금 공통 에러 페이지나 toast/alert가 없는 상태여서, ErrorResponseType 형태로 반환되지 않는 에러가 발생할 때 사용자가 에러가 반환되었음을 알 방법이 없어 'Unknown error'로 toast message라도 띄우려고 임의로 추가해 뒀습니다 ! (문구는 문의해봐야 할 것 같아요 ㅠ)

2024-08-22 14:43 UTC, MeaninGood commented on src/apis/auth/post.ts
> +    return { errorMessage: 'Unknown error' };
> 여기는 위에서 만드신 `returnError` 함수를 사용하지 않으신 것 같아요!

returnError 함수가 결국 ErrorResponseType에 해당하는 에러에 대해 LOGIN_ERROR_MESSAGE와 매핑해주기 위함인데, `emailVerification`는 정해진 에러코드가 없기 때문에 혼동을 피하고자 그대로 errorMessage를 반환하게 만들어 두었습니다.

2024-08-22 14:51 UTC, MeaninGood commented on src/app/auth/email-verification/components.tsx
> +  const [codeArray, setCodeArray] = useState(new Array(6).fill(''));
request에서 string으로 들어가야 해서, api 호출할 때 string 처리하는 대신 상태관리부터 string으로 해주었습니다

2024-08-22 15:02 UTC, MeaninGood commented on src/hooks/useUser.tsx
> +    if ('accessToken' in res) {
> `in`은 값이 undefined여도 true가 나온다는걸 알고 사용하신게 맞을까요..? 밑에도 in을 꽤 많이 사용하셨는데, 이 점을 인지하고 사용하셨다면 오케이입니다
> 
> ![image](https://private-user-images.githubusercontent.com/59170680/359165379-f7d41a82-9e3f-4b86-9fbb-06a3c18a3f12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMzg4MjYsIm5iZiI6MTcyNDMzODUyNiwicGF0aCI6Ii81OTE3MDY4MC8zNTkxNjUzNzktZjdkNDFhODItOWUzZi00Yjg2LTlmYmItMDZhM2MxOGEzZjEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDE0NTUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNmY2ZWJlZDM5Mzk1ZDI5MjZmOTNjOThhZGM2NjFjNmNiZDUwYTg3MTBiYzZjNjA4ZTFjODg4NjNhZDlmNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q19BcTmhW7aXO8GBx0tG-8feKHC8UJ5ojo8eeEBWoJ4)

<img width="464" alt="image" src="https://github.com/user-attachments/assets/2bbcd773-fd60-47c1-851c-9b77217b5a97">
네네 윗부분 res에 애초부터 리턴 타입을 명시해 두었기 떄문에, 여기서는 object의 키를 체크하는 게 아닌 타입 가드의 용도로 사용한 것입니다 ! (accessToken은 string 타입만 허용하고, undefined 불가)

2024-08-22 15:04 UTC, MeaninGood commented on src/hooks/useUser.tsx
> +    if ('accessToken' in res) {
> > `in`은 값이 undefined여도 true가 나온다는걸 알고 사용하신게 맞을까요..? 밑에도 in을 꽤 많이 사용하셨는데, 이 점을 인지하고 사용하셨다면 오케이입니다
> > ![image](https://private-user-images.githubusercontent.com/59170680/359165379-f7d41a82-9e3f-4b86-9fbb-06a3c18a3f12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMzg4MjYsIm5iZiI6MTcyNDMzODUyNiwicGF0aCI6Ii81OTE3MDY4MC8zNTkxNjUzNzktZjdkNDFhODItOWUzZi00Yjg2LTlmYmItMDZhM2MxOGEzZjEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDE0NTUyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNmY2ZWJlZDM5Mzk1ZDI5MjZmOTNjOThhZGM2NjFjNmNiZDUwYTg3MTBiYzZjNjA4ZTFjODg4NjNhZDlmNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q19BcTmhW7aXO8GBx0tG-8feKHC8UJ5ojo8eeEBWoJ4)
> 
> <img alt="image" width="464" src="https://private-user-images.githubusercontent.com/92563854/360521539-2bbcd773-fd60-47c1-851c-9b77217b5a97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMzkyOTIsIm5iZiI6MTcyNDMzODk5MiwicGF0aCI6Ii85MjU2Mzg1NC8zNjA1MjE1MzktMmJiY2Q3NzMtZmQ2MC00N2MxLTg1MWMtOWI3NzIxN2I1YTk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDE1MDMxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2NTRlNjVjNDllMzFjYzUxYjZmN2YwNjQ2N2Q4YWYwZTczYzlhZjM0M2QxMzM0ZDI2MzBkNDBjMDE3ZmJjYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CFQD_YiTuI31YIc1HcqKHCB1Bqs_f_MYaOJIwAv0KUE"> 네네 윗부분 res에 애초부터 리턴 타입을 명시해 두었기 떄문에, 여기서는 타입 가드의 용도로 사용한 것입니다 ! (accessToken은 string 타입만 허용하고, undefined 불가)

<img width="198" alt="image" src="https://github.com/user-attachments/assets/8763cbc4-b388-46e4-931f-e0a94d3fa433">

2024-08-26 08:41 UTC, MeaninGood commented
> #### 눈에 보이는 이슈가 꽤 있어서... 고생하셨는데 괜히 트집 왕창 잡는 것 같아 죄송합니다 😢
> 1. 아직도 린트가 안먹어요.... 왜죠
>    ![image](https://private-user-images.githubusercontent.com/59170680/359145117-b9249f7d-d286-4567-9d32-996c828a76f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NTU2MDksIm5iZiI6MTcyNDY1NTMwOSwicGF0aCI6Ii81OTE3MDY4MC8zNTkxNDUxMTctYjkyNDlmN2QtZDI4Ni00NTY3LTlkMzItOTk2YzgyOGE3NmYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDA2NTUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3NmNlNGUzYTc5NjZmODIxMjMxMmQwZmVmNjBkYWFjOGVmMTY3YWIwZDdiMTFmMjBjZDY4NGRjN2UyYjNkMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Aj0phahekMinq4A109-b-R6B2WeoLJV6ex5fOXPeTKI)
> 2. 혹시 이메일 전송 잘 되나요? 저는 안오네요.. 이거 때문에 비밀번호  (추가 : 오긴 하는데 굉장히 오래 걸립니다... 한 10분 걸리는 것 같아요)
> 3. 가입한 이메일을 입력해도 이메일이 전송됩니다 ㅜ
> 4. 인증번호 입력 화면에서 백스페이스를 누르면 이전 input으로 돌아가야 할 것 같아요!
>    ![image](https://private-user-images.githubusercontent.com/59170680/359140538-594903ae-8bcc-4b31-904d-10bf66108072.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NTU2MDksIm5iZiI6MTcyNDY1NTMwOSwicGF0aCI6Ii81OTE3MDY4MC8zNTkxNDA1MzgtNTk0OTAzYWUtOGJjYy00YjMxLTkwNGQtMTBiZjY2MTA4MDcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDA2NTUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzNjcxNGJiZWVmMWI5MzU2N2U0YWZhZTA3MjNjMzE1NDExMWYzNjljNTc5NzNhZDk1ZDk2YjA3MWU1ZjZkMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZN0geIgos1t5kUCHuTdErcZu0UaeXkUKQ9dD87XVjZ8)
> 5. 시간이 만료된 후 재전송 되면 타이머가 재시작 해야 할 것 같아요! (시간이 만료되지 않았을 때 재전송을 하면 타이머가 초기화 되네요)
>    ![image](https://private-user-images.githubusercontent.com/59170680/359142045-caa0696b-0593-4ba2-b4f7-daa41fe13653.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NTU2MDksIm5iZiI6MTcyNDY1NTMwOSwicGF0aCI6Ii81OTE3MDY4MC8zNTkxNDIwNDUtY2FhMDY5NmItMDU5My00YmEyLWI0ZjctZGFhNDFmZTEzNjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDA2NTUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmNjJkNDYwOGIwZTQ4NDBiNWZiMTNlYjczZWVhNTUzNGU5MTIyNDc1MWQ5OTA3ODMzZjk1ZmZiZTUwNGZhMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PRH7nCV4UVdWHWnHOU2zP3_iokWJ0euj1iGpGbA01I4)
> 6. 이메일 입력 페이지에서 이메일 형식이 유효하지 않으면 아예 api 요청을 보내지 않는게 낫지 않을까요? 백엔드에서 검증을 한다고 해도 프론트에서 검증을 해서 의미없는 api 요청을 줄이는 것도 좋을 것 같아요
> 7. 비밀번호 유효성 검증 에러 문구가 사라지지 않네요 ㅠ
>    ![image](https://private-user-images.githubusercontent.com/59170680/359145770-3b70c2d3-a61f-486b-b535-3b3402905f92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NTU2MDksIm5iZiI6MTcyNDY1NTMwOSwicGF0aCI6Ii81OTE3MDY4MC8zNTkxNDU3NzAtM2I3MGMyZDMtYTYxZi00ODZiLWI1MzUtM2IzNDAyOTA1ZjkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDA2NTUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjZWI4ZTI2MDRjY2QyZWVmMWZkMTU3ZjhhNDRlN2IxZmMxNGMwODVmMmY0MzljZDZlNTU3ODVkY2ExYTk1YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w-4O18OnToclKXXZAI_vZUMPCAwq9F1b-F3QVzsqrO0)
> 8. 위의 7번 이슈 때문에 완료 버튼도 활성화가 안돼요
>    ![image](https://private-user-images.githubusercontent.com/59170680/359146205-428dfb5e-3ec6-44ad-b7c8-ed8fe0376d2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NTU2MDksIm5iZiI6MTcyNDY1NTMwOSwicGF0aCI6Ii81OTE3MDY4MC8zNTkxNDYyMDUtNDI4ZGZiNWUtM2VjNi00NGFkLWI3YzgtZWQ4ZmUwMzc2ZDJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDA2NTUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1ZjFjZTE0MjE0Y2FhMzc1NjAzNzZlZWFlYTU0NzE5ZWJhMjhjYzRkZTNiODBjY2YyMDRiN2VmNzUyMTUyYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WYft-KavrHoFFG4EczZ5D2DfB7MgoelP7ZrAxqBETWs)
> 9. 회원가입 완료 후 보여지는 모달은 아직 작업이 안된게 맞겠죠? setIsSignUp이라는 함수는 사용하고 있는데 모달은 안뜨길래...

1. 반영 완료
2, 3. 백엔드 수정 필요
4. 반영 완료
5. 이메일 유효 시간 만료 시 email 입력 페이지로 리다이렉트 하기로 하여, 재전송 로직 삭제하였습니다.
7, 8. 대문자 + 소문자 + 숫자에서 대소문자 + 숫자로 수정 완료
9. 모달 작업 진행 안 되었습니다!

2024-08-26 09:11 UTC, MeaninGood commented on src/apis/auth/post.ts
> +    return { errorMessage: 'Unknown error' };
근데 returnError 함수로 써도 무방할 것 같아서 반영했습니다~

2024-08-26 09:13 UTC, MeaninGood commented on src/apis/auth/post.ts
> +
좋습니다!

2024-08-26 09:52 UTC, MeaninGood commented on src/app/auth/password/components.tsx
> +  }, [password, confirmPassword]);
위의 코멘트에서는 early-return 을 사용헀는데요, 해당 코드에서 사용은 반대 의견입니다.

early-return 예시
```tsx
  const isButtonEnabled = useMemo(() => {
    if (!isPasswordValid(password)) return false;
    if (confirmPassword.length <= 0) return false;

    return true;

  }, [password, confirmPassword]);
```

현재 코드
```tsx
  const isButtonEnabled = useMemo(() => {
    const isValidPassword = isPasswordValid(password);
    return isValidPassword && confirmPassword.length > 0;
  }, [password, confirmPassword]);

```
위는 early-return을 적용했을 때의 코드인데요, 해석이 다음처럼 될 것 같습니다.
1. isPasswordValid(password)가 false인 경우 false를 반환한다
2. confirmPassword의 길이가 0보다 작거나 같은 경우 false를 반환한다
3. 그 외의 모든 경우 true를 반환한다.

그러나, 강조되어야 하는 건 " isPasswordValid(password)가 true이고, confirmPassword의 길이가 0보다 클 때만 true를 반환한다" 입니다.
해당 케이스에서만 true가 되어야 하는 로직이고, 이외의 상황에서는 모두 false가 된다고 인지하도록 작성하는 게 가장 명확한 것 같아요.

2024-08-26 10:15 UTC, MeaninGood commented on src/hooks/useUser.tsx
> +    if ('isVerified' in res && res.isVerified) {
'isVerified' in res : 타입가드
res.isVerified : true 체크
용도입니다~!

2024-08-26 10:27 UTC, MeaninGood commented on src/utils/parse.ts
> +  if (!emailPattern) return '';
오 이메일 형태가 아닌 경우입니다.. email이 빈스트링으로 들어오는 경우, @가 없는 경우 등등이 다 커버될 것 같아서 emailPattern 정규식으로 작성했어요 !

2024-08-27 00:07 UTC, msdio commented on src/apis/auth/post.ts
> +  return { errorMessage: 'Unknown error' };
그러면 errorMessage로 커스텀한 에러도 `ErrorResponseType` 과 동일하게 가져가면, 굳이 밑에서 `in` 을 사용해 추가적인 조건문도 작성하지 않아도 되지 않을까요..? 굳이 타입을 나누신 이유가 궁금한거였습니다

2024-08-27 00:14 UTC, msdio commented on src/apis/index.ts
> +  // baseURL: 'https://api-pitstop.site/',
@MeaninGood 이거 수정을 안하기로 결정하신건가요..? 아니면 누락하신걸까요

2024-08-27 01:12 UTC, MeaninGood commented on src/apis/auth/post.ts
> +  return { errorMessage: 'Unknown error' };
> 그러면 errorMessage로 커스텀한 에러도 `ErrorResponseType` 과 동일하게 가져가면, 굳이 밑에서 `in` 을 사용해 추가적인 조건문도 작성하지 않아도 되지 않을까요..? 굳이 타입을 나누신 이유가 궁금한거였습니다

네네 저도 다시 보니 이상해서 요부분 수정해서 커밋 남겨 둬씁니당!!! ㅎㅎㅎㅎ https://github.com/team-vera6/career-client/pull/53/commits/7304fed40ed3dae6dce1e1cac15ddf4ee040c2d3

2024-08-27 01:13 UTC, MeaninGood commented on src/apis/index.ts
> +  // baseURL: 'https://api-pitstop.site/',
이거 해람님 pr에 반영되어 있길래, 마침 컨플릭 난 김에 머지할 때 지우겠습니당~!

2024-08-27 01:14 UTC, MeaninGood commented on src/apis/index.ts
> +  // baseURL: 'https://api-pitstop.site/',
> @MeaninGood 이거 수정을 안하기로 결정하신건가요..? 아니면 누락하신걸까요

이거 해람님 pr에 반영되어 있길래, 마침 컨플릭 난 김에 머지할 때 지우겠습니당~!

2024-08-27 01:20 UTC, msdio commented on src/hooks/useUser.tsx
> +    if ('accessToken' in res) {
그 목적이라면 원래 목적은 api 요청이 성공했는지 여부에 따라 갈리는 것 같은데, 그러면 타입 가드가 아니라 try - catch로 성공했을 경우에 해당 로직이 실행되도록 하는게 낫지 않을까..? 싶긴 한데 우선 이렇게 가시죠!

2024-08-27 01:22 UTC, msdio commented on src/hooks/useUser.tsx
> +      setUserToken((prev) => ({ ...prev, accessToken: res.token as string }));
여기는 어떻게 된건가요

2024-08-27 01:28 UTC, MeaninGood commented on src/hooks/useUser.tsx
> +    if ('accessToken' in res) {
> 그 목적이라면 원래 목적은 api 요청이 성공했는지 여부에 따라 갈리는 것 같은데, 그러면 타입 가드가 아니라 try - catch로 성공했을 경우에 해당 로직이 실행되도록 하는게 낫지 않을까..? 싶긴 한데 우선 이렇게 가시죠!

에러를 이미 returnError 함수로 정제해서 보내서, reject객체를 전달받진 않습니다 ㅜㅜ ㄱ아니면 저 매핑해주는 부분을 훅으로 뺄까요 ?? 예시 코드 첨부합니당

```typescript
// 공통 error 리턴
const returnError = (err: unknown) => {
  const error = err as ErrorResponseType;

  if (LOGIN_ERROR_MESSAGE[error.code]) {
    return { errorMessage: LOGIN_ERROR_MESSAGE[error.code] };
  }
  return { errorMessage: 'Unknown error' };
};

export const login = async (email: string, password: string) => {
  try {
    const res = await typedPost<{ accessToken: string }>('/auth/sign-in', {
      email,
      password,
    });
    return res;
  } catch (err) {
    return returnError(err); // 로그인 error 시 returnError로 한번 정제
  }
};

// hook
  const userLogin = async (email: string, password: string) => {
    const res = await login(email, password);

    if ('accessToken' in res) {
      const accessToken = res.accessToken;
      localStorage.setItem('accessToken', accessToken);

      setUserToken((prev) => ({ ...prev, accessToken: res.accessToken }));
      return 'success';
    } else {
      addToast({
        message: res.errorMessage,
        iconType: 'error',
      });

      return 'error';
    }
  };
```

2024-08-27 01:33 UTC, msdio requested changes
- 컨플릭 확인 부탁드립니다!
- 패스워드 검증 로직이 대문자 소문자 둘 다 없어도 통과되는데 확인부탁드려요

2024-08-27 01:37 UTC, MeaninGood commented
> * 컨플릭 확인 부탁드립니다!
> * 패스워드 검증 로직이 대문자 소문자 둘 다 없어도 통과되는데 확인부탁드려요

![image](https://github.com/user-attachments/assets/0f0ac619-a76e-4929-b4b3-90217db1678d)
초기 대/소문자 구분으로 만들어 뒀다가, 해람님 코멘트 읽고 피그마 확인해보니 대소문자 구분이 없어 하나로 합쳤습니다!

2024-08-27 05:48 UTC, msdio commented on src/hooks/useUser.tsx
> +    if ('accessToken' in res) {
우선 이렇게 가시죠! 나중에 리팩토링 고려사항으로 메모만 해두면 될것같아요

2024-08-27 05:50 UTC, MeaninGood commented on src/hooks/useUser.tsx
> +      setUserToken((prev) => ({ ...prev, accessToken: res.token as string }));
아 res 타입을 잘못 적어가지고 ㅠ https://github.com/team-vera6/career-client/pull/53/commits/7304fed40ed3dae6dce1e1cac15ddf4ee040c2d3 요거 확인 부탁드려여 !

2024-08-27 05:50 UTC, msdio approved these changes

2024-08-27 06:08 UTC, merged